let common = system.getScript("/common");
let xbarSoc = system.getScript(`/xbar/soc/xbar_${common.getSocName()}`);

const internal_list = [
    {  name: "CMPSSA0_CTRIPL", displayName: "CMPSSA0_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA0_CTRIPH", displayName: "CMPSSA0_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA1_CTRIPL", displayName: "CMPSSA1_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA1_CTRIPH", displayName: "CMPSSA1_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA2_CTRIPL", displayName: "CMPSSA2_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA2_CTRIPH", displayName: "CMPSSA2_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA3_CTRIPL", displayName: "CMPSSA3_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA3_CTRIPH", displayName: "CMPSSA3_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA4_CTRIPL", displayName: "CMPSSA4_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA4_CTRIPH", displayName: "CMPSSA4_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA5_CTRIPL", displayName: "CMPSSA5_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA5_CTRIPH", displayName: "CMPSSA5_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA6_CTRIPL", displayName: "CMPSSA6_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA6_CTRIPH", displayName: "CMPSSA6_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA7_CTRIPL", displayName: "CMPSSA7_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA7_CTRIPH", displayName: "CMPSSA7_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA8_CTRIPL", displayName: "CMPSSA8_CTRIPL", path: "epwm_xbar", group: 0 },
    {  name: "CMPSSA8_CTRIPH", displayName: "CMPSSA8_CTRIPH", path: "epwm_xbar", group: 0 },
    {  name: "SD0_FILT0_EVT1", displayName: "SD0_FILT0_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT0_EVT2", displayName: "SD0_FILT0_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT0_CMPHZ", displayName: "SD0_FILT0_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT1_EVT1", displayName: "SD0_FILT1_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT1_EVT2", displayName: "SD0_FILT1_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT1_CMPHZ", displayName: "SD0_FILT1_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT2_EVT1", displayName: "SD0_FILT2_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT2_EVT2", displayName: "SD0_FILT2_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT2_CMPHZ", displayName: "SD0_FILT2_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT3_EVT1", displayName: "SD0_FILT3_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT3_EVT2", displayName: "SD0_FILT3_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD0_FILT3_CMPHZ", displayName: "SD0_FILT3_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT0_EVT1", displayName: "SD1_FILT0_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT0_EVT2", displayName: "SD1_FILT0_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT0_CMPHZ", displayName: "SD1_FILT0_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT1_EVT1", displayName: "SD1_FILT1_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT1_EVT2", displayName: "SD1_FILT1_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT1_CMPHZ", displayName: "SD1_FILT1_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT2_EVT1", displayName: "SD1_FILT2_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT2_EVT2", displayName: "SD1_FILT2_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT2_CMPHZ", displayName: "SD1_FILT2_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT3_EVT1", displayName: "SD1_FILT3_EVT1", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT3_EVT2", displayName: "SD1_FILT3_EVT2", path: "epwm_xbar", group: 1 },
    {  name: "SD1_FILT3_CMPHZ", displayName: "SD1_FILT3_CMPHZ", path: "epwm_xbar", group: 1 },
    {  name: "ADC0_EVT1", displayName: "ADC0_EVT1", path: "epwm_xbar", group: 2 },
    {  name: "ADC0_EVT2", displayName: "ADC0_EVT2", path: "epwm_xbar", group: 2 },
    {  name: "ADC0_EVT3", displayName: "ADC0_EVT3", path: "epwm_xbar", group: 2 },
    {  name: "ADC0_EVT4", displayName: "ADC0_EVT4", path: "epwm_xbar", group: 2 },
    {  name: "ADC1_EVT1", displayName: "ADC1_EVT1", path: "epwm_xbar", group: 2 },
    {  name: "ADC1_EVT2", displayName: "ADC1_EVT2", path: "epwm_xbar", group: 2 },
    {  name: "ADC1_EVT3", displayName: "ADC1_EVT3", path: "epwm_xbar", group: 2 },
    {  name: "ADC1_EVT4", displayName: "ADC1_EVT4", path: "epwm_xbar", group: 2 },
    {  name: "ADC2_EVT1", displayName: "ADC2_EVT1", path: "epwm_xbar", group: 2 },
    {  name: "ADC2_EVT2", displayName: "ADC2_EVT2", path: "epwm_xbar", group: 2 },
    {  name: "ADC2_EVT3", displayName: "ADC2_EVT3", path: "epwm_xbar", group: 2 },
    {  name: "ADC2_EVT4", displayName: "ADC2_EVT4", path: "epwm_xbar", group: 2 },
    {  name: "EPWM0_TRIPOUT", displayName: "EPWM0_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM1_TRIPOUT", displayName: "EPWM1_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM2_TRIPOUT", displayName: "EPWM2_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM3_TRIPOUT", displayName: "EPWM3_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM4_TRIPOUT", displayName: "EPWM4_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM5_TRIPOUT", displayName: "EPWM5_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM6_TRIPOUT", displayName: "EPWM6_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM7_TRIPOUT", displayName: "EPWM7_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM8_TRIPOUT", displayName: "EPWM8_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "EPWM9_TRIPOUT", displayName: "EPWM9_TRIPOUT", path: "epwm_xbar", group: 4 },
    {  name: "DEL0_TRIP", displayName: "DEL0_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL1_TRIP", displayName: "DEL1_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL2_TRIP", displayName: "DEL2_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL3_TRIP", displayName: "DEL3_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL4_TRIP", displayName: "DEL4_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL5_TRIP", displayName: "DEL5_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL6_TRIP", displayName: "DEL6_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL7_TRIP", displayName: "DEL7_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL8_TRIP", displayName: "DEL8_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL9_TRIP", displayName: "DEL9_TRIP", path: "epwm_xbar", group: 5 },
    {  name: "DEL0_ACTIVE", displayName: "DEL0_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL1_ACTIVE", displayName: "DEL1_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL2_ACTIVE", displayName: "DEL2_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL3_ACTIVE", displayName: "DEL3_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL4_ACTIVE", displayName: "DEL4_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL5_ACTIVE", displayName: "DEL5_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL6_ACTIVE", displayName: "DEL6_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL7_ACTIVE", displayName: "DEL7_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL8_ACTIVE", displayName: "DEL8_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "DEL9_ACTIVE", displayName: "DEL9_ACTIVE", path: "epwm_xbar", group: 6 },
    {  name: "EQEP0_ERR", displayName: "EQEP0_ERR", path: "epwm_xbar", group: 7 },
    {  name: "EQEP1_ERR", displayName: "EQEP1_ERR", path: "epwm_xbar", group: 7 },
    {  name: "FSIRX0_RX_TRIG0", displayName: "FSIRX0_RX_TRIG0", path: "epwm_xbar", group: 7 },
    {  name: "FSIRX0_RX_TRIG1", displayName: "FSIRX0_RX_TRIG1", path: "epwm_xbar", group: 7 },
    {  name: "FSIRX0_RX_TRIG2", displayName: "FSIRX0_RX_TRIG2", path: "epwm_xbar", group: 7 },
    {  name: "FSIRX0_RX_TRIG3", displayName: "FSIRX0_RX_TRIG3", path: "epwm_xbar", group: 7 },
    {  name: "ECAP0_TRIPOUT", displayName: "ECAP0_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP1_TRIPOUT", displayName: "ECAP1_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP2_TRIPOUT", displayName: "ECAP2_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP3_TRIPOUT", displayName: "ECAP3_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP4_TRIPOUT", displayName: "ECAP4_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP5_TRIPOUT", displayName: "ECAP5_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP6_TRIPOUT", displayName: "ECAP6_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "ECAP7_TRIPOUT", displayName: "ECAP7_TRIPOUT", path: "epwm_xbar", group: 7 },
    {  name: "SYNCOUTXBAR0", displayName: "SYNCOUTXBAR0", path: "epwm_xbar", group: 8 },
    {  name: "SYNCOUTXBAR1", displayName: "SYNCOUTXBAR1", path: "epwm_xbar", group: 8 },
    {  name: "SOCAXBAR_SOCA", displayName: "SOCAXBAR_SOCA", path: "epwm_xbar", group: 8 },
    {  name: "SOCAXBAR_SOCB", displayName: "SOCAXBAR_SOCB", path: "epwm_xbar", group: 8 },
];

let xbarProperties = {
    masterXbarList: ["input_xbar"],
    outputInstanceList: [
        { name: "EPWM_XBAR", count: 30},
    ],
    duplicatesPresent: false,
    moduleString: "epwm_xbar",
}

function getOptionList(calledBy) {
    return xbarSoc.getOptionListSoc(calledBy, xbarProperties, internal_list);
}

function getConfigArr() {
    return xbarSoc.getXbarInstanceConfig(xbarProperties);
}

function supportXbarConfig(outputSelected, instance, count) {
    return xbarSoc.supportXbarConfigSoc(outputSelected, instance, xbarProperties, count);
}

exports = {
    getConfigArr,
    getOptionList,
    supportXbarConfig,
};
